/**
 *
 * so this is where you define the package details for CONNECT platform.
 * these details are confined to 'module.exports.platform', to allow for packages
 * that would work outside of the context of CONNECT platform as well.
 *
 */
module.exports.platform = {
  /**
   *
   * these are the configurations of your package.
   *
   */
  config: {
    /**
     *
     * these are the nodes introduced by your package.
     * you should specify the nodes your package offers based on
     * their type. node types can be one of the following:
     *
     * - native: i.e. nodes written in javascript.
     * - json: i.e. nodes generated by CONNECT platform itself.
     * - module: i.e. other CONNECT packages your package is dependant on. these can
     *          be included locally or can be external packages, in which case the platform
     *          will try to fetch and install them upon initialization.
     *
     */
    nodes : {
      /**
       *
       * reference native modules (and json modules as well) relative to root of your
       * package, without the extension.
       *
       */
      native : [
        'ECR/token/get',

        'ECR/repository/create',
        'ECR/repository/delete',
        'ECR/repository/describe',
        'ECR/repository/policy/set',
        'ECR/repository/policy/create/allowPushPull',
        
        'ECR/repositories/describe'
       ]
    },
    /**
     *
     * aliases help you declare more generic addresses for your nodes.
     * for example, you might be aliasing '/firestore/insert' to '/db/insert',
     * so that other nodes and packages of the user will be using them without
     * being aware that 'db' is actually 'firestore'.
     *
     */
    aliases: {
      '/ecr/token/get': '/aws/ECR/token/get',
      
      '/ecr/repository/create': '/aws/ECR/repository/create',
      '/ecr/repository/delete': '/aws/ECR/repository/delete',
      '/ecr/repository/describe': '/aws/ECR/repository/describe',
      '/ecr/repository/policy/set': '/aws/ECR/repository/policy/set',
      '/ecr/repository/policy/create/allowPushPull': '/aws/ECR/repository/policy/create/allowPushPull',

      '/ecr/repositories/describe': '/aws/ECR/repositories/describe'
    }
  },
  hints: {
    setup:
  `Should work if you provide the correct configuration as shown below.<br>
  Otherwise, check the sample configuration below and <a href="https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/Credentials.html">this page (credentials)</a>/<a href="https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS.html#config-property">this page (AWS.conig)</a> for a more detailled description on all the options.`,
  sampleConfig: {
      "aws": {
        "credentials": {
          "accessKeyId": "<ACCESS KEY ID>",
          "secretAccessKey": "<SECRET ACCESS KEY>",
          "sessionToken": "<OPTIONAL SESSION TOKEN>"
        },
        "region": "eu-central-1"
      }
    }
  }
}
